/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ['@law-ai/shared'],
  // Expose BE URL to client via NEXT_PUBLIC_*
  env: {
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000',
  },
  // Allow next/image to load QR codes generated by VietQR / qrserver.
  // checkout-modal renders these via <Image unoptimized> — we only need
  // remotePatterns so the optimizer doesn't reject the upstream URL.
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'img.vietqr.io' },
      { protocol: 'https', hostname: 'api.qrserver.com' },
    ],
  },
  experimental: {
    // Allow server actions on more routes if needed
  },
  output: 'standalone',
};

export default nextConfig;
